backend:
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**/*'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

mobile:
  - changed-files:
      - any-glob-to-any-file: 'apps/mobile/**/*'

shared:
  - changed-files:
      - any-glob-to-any-file: 'packages/**/*'

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - 'docker-compose.yml'
          - '.github/workflows/*'